package view;

/**
 *
 * @author Pelle
 */
public class AdminCatagoryGUI extends javax.swing.JPanel {

    /**
     * Creates new form AdminCatagoryGUI
     */
    GUI gui;

    /**
     * Constructor of AdminCategoryGUI
     * @param gui
     */
    public AdminCatagoryGUI(GUI gui) {
        initComponents();
        this.gui = gui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CatagoryJP = new javax.swing.JPanel();
        instructorBTN = new javax.swing.JButton();
        productBTN = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        CatagoryJP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CatagoryJP.setLayout(new java.awt.GridBagLayout());

        instructorBTN.setText("Instrukør");
        instructorBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                instructorBTNMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 175;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(48, 90, 0, 87);
        CatagoryJP.add(instructorBTN, gridBagConstraints);

        productBTN.setText("Vare");
        productBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBTNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 197;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(6, 90, 170, 87);
        CatagoryJP.add(productBTN, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        add(CatagoryJP, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void instructorBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructorBTNMouseReleased
        
        InstructorGUI adminGui = new InstructorGUI();
        
            gui.backPanel.removeAll();
            gui.backPanel.repaint();
            gui.backPanel.add(adminGui);
            gui.backPanel.repaint();
            gui.setVisible(true);
        
        adminGui.setVisible(true);
    }//GEN-LAST:event_instructorBTNMouseReleased

    private void productBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBTNActionPerformed
        
            CreateProductGUI createProductGui = new CreateProductGUI();
        
            gui.backPanel.removeAll();
            gui.backPanel.repaint();
            gui.backPanel.add(createProductGui);
            gui.backPanel.repaint();
            gui.setVisible(true);
        
            createProductGui.setVisible(true);
    }//GEN-LAST:event_productBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CatagoryJP;
    private javax.swing.JButton instructorBTN;
    private javax.swing.JButton productBTN;
    // End of variables declaration//GEN-END:variables
}
